# Generated by Django 4.0 on 2021-12-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_remove_profile_address_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.customuser', verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.customuser', verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/post_images', verbose_name='عکس')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('categories', models.ManyToManyField(db_table='Post_Categories', related_name='posts', to='blog.Category', verbose_name='دسته\u200cبندی\u200cها')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.customuser', verbose_name='نویسنده')),
                ('tags', models.ManyToManyField(blank=True, db_table='Post_Tags', related_name='posts', to='blog.Tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
                'ordering': ['-date_created'],
            },
        ),
    ]
