# Generated by Django 4.0 on 2021-12-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='shop_management.shoptype', verbose_name='نوع فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
