# Generated by Django 4.0 on 2021-12-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0002_alter_shop_type_alter_shoptype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
