# Generated by Django 4.0 on 2021-12-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_slug'),
        ('shop_management', '0006_product_productcategory_alter_shop_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='accounts.customuser', verbose_name='صاحب فروشگاه'),
        ),
    ]
