# Generated by Django 4.0 on 2021-12-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0007_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصول'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته\u200cبندی محصول', 'verbose_name_plural': 'دسته\u200cبندی محصول'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه\u200c'},
        ),
        migrations.AlterModelOptions(
            name='shoptype',
            options={'verbose_name': 'نوع فروشگاه', 'verbose_name_plural': '\u200cانواع فروشگاه\u200c'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop_management.productcategory', verbose_name='دسته\u200cبندی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_management.shop', verbose_name='فروشگاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='موجودی محصول'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop_management.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('slug', 'parent')},
        ),
    ]
