# Generated by Django 4.0 on 2021-12-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0009_alter_product_created_at_alter_product_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop_management.productcategory', verbose_name='دسته\u200cبندی اصلی'),
        ),
    ]
