# Generated by Django 4.0 on 2021-12-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0010_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='برند'),
        ),
    ]
