# Generated by Django 3.2.10 on 2022-01-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0012_alter_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(help_text='در انتخاب این مورد دقت کنید، امکان تغییر نوع فروشگاه در آینده وجود نخواهد داشت.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shop_management.shoptype', verbose_name='نوع فروشگاه'),
        ),
    ]
