# Generated by Django 3.2.10 on 2022-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0013_alter_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام فروشگاه'),
        ),
    ]
