# Generated by Django 3.2.10 on 2022-01-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0016_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/product_images', verbose_name='عکس محصول'),
        ),
    ]
