# Generated by Django 3.2.10 on 2022-01-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0019_auto_20220115_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود بودن'),
        ),
    ]
