# Generated by Django 3.2.10 on 2022-01-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0020_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_images', verbose_name='عکس محصول'),
        ),
    ]
