# Generated by Django 3.2.10 on 2022-01-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0020_alter_product_is_available'),
        ('shop', '0006_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shop.CartItem', to='shop_management.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_management.shop', verbose_name='فروشگاه'),
        ),
    ]
