# Generated by Django 3.2.10 on 2022-01-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0020_alter_product_is_available'),
        ('shop', '0007_auto_20220115_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop_management.shop', verbose_name='فروشگاه'),
        ),
    ]
