# Generated by Django 3.2.10 on 2022-01-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220120_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ خرید'),
        ),
    ]
