# Generated by Django 4.0 on 2021-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_salesman',
            field=models.BooleanField(default=False, verbose_name='فروشنده بودن'),
        ),
    ]
