# Generated by Django 4.0 on 2021-12-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile_pictures', verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.customuser', verbose_name='کاربر')),
            ],
        ),
    ]
