# Generated by Django 4.0 on 2021-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_alter_profile_options_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(related_name='user', to='accounts.Address', verbose_name='آدرس'),
        ),
    ]
