# Generated by Django 4.0 on 2021-12-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_options_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='اسلاگ'),
        ),
    ]
