# Generated by Django 4.0 on 2021-12-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_customerprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.Address', verbose_name='آدرس'),
        ),
    ]
