# Generated by Django 3.2.10 on 2022-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_is_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_salesman',
            field=models.BooleanField(default=False, verbose_name='فروشنده'),
        ),
    ]
