# Generated by Django 3.2.10 on 2022-01-27 11:09

import accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('phone_number', 'Phone')], default='phone_number', max_length=20)),
                ('receiver', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('code', models.CharField(default=accounts.models.generate_totp, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='passed_phone_number_verification',
            field=models.BooleanField(default=False, verbose_name='شماره موبایل تأیید شده؟'),
        ),
    ]
