# Generated by Django 3.2.10 on 2022-01-27 11:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220127_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totprequest',
            options={'verbose_name': 'درخواست\u200cهای رمز یکبارمصرف', 'verbose_name_plural': 'درخواست\u200cهای رمز یکبارمصرف'},
        ),
        migrations.AlterField(
            model_name='totprequest',
            name='code',
            field=models.CharField(default=accounts.models.generate_totp, max_length=4, verbose_name='کد یکبار مصرف'),
        ),
        migrations.AlterField(
            model_name='totprequest',
            name='receiver',
            field=models.CharField(max_length=11, verbose_name='دریافت\u200cکننده'),
        ),
    ]
