# Generated by Django 3.2.10 on 2022-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220127_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totprequest',
            name='receiver',
            field=models.CharField(max_length=20, verbose_name='دریافت\u200cکننده'),
        ),
    ]
