# Generated by Django 3.2.10 on 2022-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_totprequest_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totprequest',
            options={'verbose_name': 'درخواست\u200cهای رمز یکبار مصرف', 'verbose_name_plural': 'درخواست\u200cهای رمز یکبار مصرف'},
        ),
        migrations.AlterField(
            model_name='totprequest',
            name='channel',
            field=models.CharField(choices=[('phone_number', 'Phone')], default='phone_number', max_length=20, verbose_name='از طریق'),
        ),
        migrations.AlterField(
            model_name='totprequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
